# Generated by Django 4.2.21 on 2025-05-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE_IRIS', models.CharField(max_length=10, unique=True)),
                ('LIB_IRIS', models.CharField(max_length=255)),
                ('TYP_IRIS', models.CharField(max_length=50)),
                ('GRD_QUART', models.CharField(max_length=100)),
                ('DEPCOM', models.CharField(max_length=10)),
                ('LIBCOM', models.CharField(max_length=255)),
                ('UU2020', models.CharField(max_length=10)),
                ('REG', models.CharField(max_length=100)),
                ('DEP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Naf2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=2, unique=True)),
                ('LIBELLE', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPERATEUR', models.CharField(max_length=10)),
                ('ANNEE', models.CharField(max_length=10)),
                ('FILIERE', models.CharField(max_length=10)),
                ('CODE_CATEGORIE_CONSOMMATION', models.CharField(max_length=10)),
                ('CONSO', models.CharField(max_length=10)),
                ('PDL', models.CharField(max_length=10)),
                ('INDQUAL', models.CharField(max_length=10)),
                ('CODE_SECTEUR_NAF2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_pinguin.naf2', to_field='CODE')),
                ('IRIS_CODE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_pinguin.iris', to_field='CODE_IRIS')),
            ],
        ),
        migrations.CreateModel(
            name='Electricite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPERATEUR', models.CharField(max_length=10)),
                ('ANNEE', models.CharField(max_length=10)),
                ('FILIERE', models.CharField(max_length=10)),
                ('CODE_CATEGORIE_CONSOMMATION', models.CharField(max_length=10)),
                ('CODE_GRAND_SECTEUR', models.CharField(max_length=10)),
                ('CONSO', models.CharField(max_length=10)),
                ('PDL', models.CharField(max_length=10)),
                ('INDQUAL', models.CharField(max_length=10)),
                ('CODE_SECTEUR_NAF2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_pinguin.naf2', to_field='CODE')),
                ('IRIS_CODE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_pinguin.iris', to_field='CODE_IRIS')),
            ],
        ),
        migrations.CreateModel(
            name='Chaleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPERATEUR', models.CharField(max_length=10)),
                ('ANNEE', models.CharField(max_length=10)),
                ('FILIERE', models.CharField(max_length=10)),
                ('CONSO', models.CharField(max_length=10)),
                ('PDL', models.CharField(max_length=10)),
                ('IRIS_CODE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_pinguin.iris', to_field='CODE_IRIS')),
            ],
        ),
    ]
