# Generated by Django 4.2.21 on 2025-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pinguin', '0002_alter_naf2_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaleur',
            name='CONSO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chaleur',
            name='PDL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='ANNEE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='CODE_CATEGORIE_CONSOMMATION',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='CODE_GRAND_SECTEUR',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='CONSO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='FILIERE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='INDQUAL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='OPERATEUR',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='PDL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='ANNEE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='CODE_CATEGORIE_CONSOMMATION',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='CONSO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='FILIERE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='INDQUAL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='OPERATEUR',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='PDL',
            field=models.FloatField(),
        ),
    ]
