# Generated by Django 4.2.21 on 2025-05-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pinguin', '0003_alter_chaleur_conso_alter_chaleur_pdl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaleur',
            name='FILIERE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chaleur',
            name='OPERATEUR',
            field=models.CharField(max_length=100),
        ),
    ]
