# Generated by Django 4.2.21 on 2025-05-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pinguin', '0004_alter_chaleur_filiere_alter_chaleur_operateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naf2',
            name='CODE',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
