# Generated by Django 4.2.21 on 2025-05-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pinguin', '0005_alter_naf2_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricite',
            name='CODE_SECTEUR_NAF2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_pinguin.naf2', to_field='CODE'),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='CODE_SECTEUR_NAF2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_pinguin.naf2', to_field='CODE'),
        ),
    ]
