# Generated by Django 4.2.21 on 2025-05-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pinguin', '0006_alter_electricite_code_secteur_naf2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naf2',
            name='CODE',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
