# Generated by Django 4.2.21 on 2025-06-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pinguin', '0007_alter_naf2_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaleur',
            name='IRIS_CODE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_pinguin.iris', to_field='CODE_IRIS'),
        ),
        migrations.AlterField(
            model_name='electricite',
            name='IRIS_CODE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_pinguin.iris', to_field='CODE_IRIS'),
        ),
        migrations.AlterField(
            model_name='gaz',
            name='IRIS_CODE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_pinguin.iris', to_field='CODE_IRIS'),
        ),
    ]
